### ISSUE TITLE
CMakeLists + Doxyfile + Folder structure

### ISSUE THREAD

**Issue by clarascherrer** [EPFL-SV-cpp-projects/Team_14#6]

**Comment by sspoerri** [comment]
Waiting for .cpp filenames and unittest filenames in order to define the build targets.
The documentation can be generated with "make doc".

**Comment by sspoerri** [comment]
Added folder test with unittest template because empty folder cannot be commited (see https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F).
